/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataAlbum(tabelAlbum, "SELECT*FROM album");
        mycode.tampilDataArtist(tabelArtist, "SELECT*FROM artist");
        mycode.tampilDataSong(tabelSong, "SELECT*FROM playlistsong");
        mycode.tampilDataCategory(tabelCategory, "SELECT*FROM playlistsongcategory");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlArtis = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDescArtist = new javax.swing.JTextField();
        txtNameArtist = new javax.swing.JTextField();
        txtStatusArtist = new javax.swing.JTextField();
        btnHpsArt = new javax.swing.JButton();
        btnSmpnArt = new javax.swing.JButton();
        btnUbhArt = new javax.swing.JButton();
        txtCariArtist = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelArtist = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIdArtist = new javax.swing.JTextField();
        pnlAlbum = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNameAlbum = new javax.swing.JTextField();
        txtArtistIdAlbum = new javax.swing.JTextField();
        txtDescAlbum = new javax.swing.JTextField();
        btnHpsAlbum = new javax.swing.JButton();
        btnSmpnAlbum = new javax.swing.JButton();
        btnUbhAlbum = new javax.swing.JButton();
        txtCariAlbum = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelAlbum = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtIdAlbum = new javax.swing.JTextField();
        txtStatusAlbum = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pnlKategori = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtDescCategory = new javax.swing.JTextField();
        txtNameCategory = new javax.swing.JTextField();
        txtStatusCategory = new javax.swing.JTextField();
        btnHpsCategory = new javax.swing.JButton();
        btnSmpnCategory = new javax.swing.JButton();
        btnUbhCategory = new javax.swing.JButton();
        txtCariCategory = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelCategory = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtIdCategory = new javax.swing.JTextField();
        pnlLagu = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtAlbumIdSong = new javax.swing.JTextField();
        txtCategoryIdSong = new javax.swing.JTextField();
        txtTitleSong = new javax.swing.JTextField();
        btnHpsSong = new javax.swing.JButton();
        btnSmpnSong = new javax.swing.JButton();
        btnUbhSong = new javax.swing.JButton();
        txtCariSong = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelSong = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtIdSong = new javax.swing.JTextField();
        txtStatusSong = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtFileSong = new javax.swing.JTextField();
        txtDurationSong = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnArtis = new javax.swing.JButton();
        btnAlbum = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLagu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlArtis.setBackground(new java.awt.Color(51, 255, 255));
        pnlArtis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Status");
        pnlArtis.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 132, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Deskripsi");
        pnlArtis.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 89, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nama Artis");
        pnlArtis.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtDescArtist.setBackground(new java.awt.Color(255, 255, 255));
        txtDescArtist.setForeground(new java.awt.Color(0, 0, 0));
        pnlArtis.add(txtDescArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNameArtist.setBackground(new java.awt.Color(255, 255, 255));
        txtNameArtist.setForeground(new java.awt.Color(0, 0, 0));
        txtNameArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameArtistActionPerformed(evt);
            }
        });
        pnlArtis.add(txtNameArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtStatusArtist.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusArtist.setForeground(new java.awt.Color(0, 0, 0));
        pnlArtis.add(txtStatusArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsArt.setText("HAPUS");
        btnHpsArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsArtActionPerformed(evt);
            }
        });
        pnlArtis.add(btnHpsArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnArt.setText("SIMPAN");
        btnSmpnArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnArtActionPerformed(evt);
            }
        });
        pnlArtis.add(btnSmpnArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhArt.setText("UBAH");
        btnUbhArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhArtActionPerformed(evt);
            }
        });
        pnlArtis.add(btnUbhArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariArtist.setBackground(new java.awt.Color(255, 255, 255));
        txtCariArtist.setForeground(new java.awt.Color(0, 0, 0));
        txtCariArtist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariArtistKeyReleased(evt);
            }
        });
        pnlArtis.add(txtCariArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, -1));

        tabelArtist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelArtist);

        pnlArtis.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 480, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Artis");
        pnlArtis.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdArtist.setBackground(new java.awt.Color(255, 255, 255));
        txtIdArtist.setForeground(new java.awt.Color(0, 0, 0));
        txtIdArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdArtistActionPerformed(evt);
            }
        });
        pnlArtis.add(txtIdArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlArtis, "card4");

        pnlAlbum.setBackground(new java.awt.Color(51, 255, 255));
        pnlAlbum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Deskripsi");
        pnlAlbum.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Nama Album");
        pnlAlbum.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Artist ID ");
        pnlAlbum.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNameAlbum.setBackground(new java.awt.Color(255, 255, 255));
        txtNameAlbum.setForeground(new java.awt.Color(0, 0, 0));
        pnlAlbum.add(txtNameAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtArtistIdAlbum.setBackground(new java.awt.Color(255, 255, 255));
        txtArtistIdAlbum.setForeground(new java.awt.Color(0, 0, 0));
        txtArtistIdAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistIdAlbumActionPerformed(evt);
            }
        });
        pnlAlbum.add(txtArtistIdAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtDescAlbum.setBackground(new java.awt.Color(255, 255, 255));
        txtDescAlbum.setForeground(new java.awt.Color(0, 0, 0));
        pnlAlbum.add(txtDescAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsAlbum.setText("HAPUS");
        btnHpsAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsAlbumActionPerformed(evt);
            }
        });
        pnlAlbum.add(btnHpsAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnAlbum.setText("SIMPAN");
        btnSmpnAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnAlbumActionPerformed(evt);
            }
        });
        pnlAlbum.add(btnSmpnAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhAlbum.setText("UBAH");
        btnUbhAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhAlbumActionPerformed(evt);
            }
        });
        pnlAlbum.add(btnUbhAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariAlbum.setBackground(new java.awt.Color(255, 255, 255));
        txtCariAlbum.setForeground(new java.awt.Color(0, 0, 0));
        txtCariAlbum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariAlbumKeyReleased(evt);
            }
        });
        pnlAlbum.add(txtCariAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 370, -1));

        tabelAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelAlbum);

        pnlAlbum.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 480, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Album");
        pnlAlbum.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdAlbum.setBackground(new java.awt.Color(255, 255, 255));
        txtIdAlbum.setForeground(new java.awt.Color(0, 0, 0));
        txtIdAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAlbumActionPerformed(evt);
            }
        });
        pnlAlbum.add(txtIdAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtStatusAlbum.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusAlbum.setForeground(new java.awt.Color(0, 0, 0));
        pnlAlbum.add(txtStatusAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Status");
        pnlAlbum.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, -1));

        Content.add(pnlAlbum, "card3");

        pnlKategori.setBackground(new java.awt.Color(51, 255, 255));
        pnlKategori.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Status");
        pnlKategori.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Deskripsi");
        pnlKategori.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Nama Kategori");
        pnlKategori.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtDescCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtDescCategory.setForeground(new java.awt.Color(0, 0, 0));
        pnlKategori.add(txtDescCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNameCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtNameCategory.setForeground(new java.awt.Color(0, 0, 0));
        txtNameCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCategoryActionPerformed(evt);
            }
        });
        pnlKategori.add(txtNameCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtStatusCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusCategory.setForeground(new java.awt.Color(0, 0, 0));
        pnlKategori.add(txtStatusCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsCategory.setText("HAPUS");
        btnHpsCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsCategoryActionPerformed(evt);
            }
        });
        pnlKategori.add(btnHpsCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnCategory.setText("SIMPAN");
        btnSmpnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnCategoryActionPerformed(evt);
            }
        });
        pnlKategori.add(btnSmpnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhCategory.setText("UBAH");
        btnUbhCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhCategoryActionPerformed(evt);
            }
        });
        pnlKategori.add(btnUbhCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtCariCategory.setForeground(new java.awt.Color(0, 0, 0));
        txtCariCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariCategoryKeyReleased(evt);
            }
        });
        pnlKategori.add(txtCariCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, -1));

        tabelCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabelCategory);

        pnlKategori.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 480, 155));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("ID Kategori");
        pnlKategori.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCategory.setForeground(new java.awt.Color(0, 0, 0));
        txtIdCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCategoryActionPerformed(evt);
            }
        });
        pnlKategori.add(txtIdCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlKategori, "card5");

        pnlLagu.setBackground(new java.awt.Color(51, 255, 255));
        pnlLagu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Judul Lagu");
        pnlLagu.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Album ID");
        pnlLagu.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Kategori ID ");
        pnlLagu.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtAlbumIdSong.setBackground(new java.awt.Color(255, 255, 255));
        txtAlbumIdSong.setForeground(new java.awt.Color(0, 0, 0));
        pnlLagu.add(txtAlbumIdSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtCategoryIdSong.setBackground(new java.awt.Color(255, 255, 255));
        txtCategoryIdSong.setForeground(new java.awt.Color(0, 0, 0));
        txtCategoryIdSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryIdSongActionPerformed(evt);
            }
        });
        pnlLagu.add(txtCategoryIdSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTitleSong.setBackground(new java.awt.Color(255, 255, 255));
        txtTitleSong.setForeground(new java.awt.Color(0, 0, 0));
        pnlLagu.add(txtTitleSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsSong.setText("HAPUS");
        btnHpsSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsSongActionPerformed(evt);
            }
        });
        pnlLagu.add(btnHpsSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnSong.setText("SIMPAN");
        btnSmpnSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnSongActionPerformed(evt);
            }
        });
        pnlLagu.add(btnSmpnSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhSong.setText("UBAH");
        btnUbhSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhSongActionPerformed(evt);
            }
        });
        pnlLagu.add(btnUbhSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariSong.setBackground(new java.awt.Color(255, 255, 255));
        txtCariSong.setForeground(new java.awt.Color(0, 0, 0));
        txtCariSong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariSongKeyReleased(evt);
            }
        });
        pnlLagu.add(txtCariSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelSong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelSong);

        pnlLagu.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 480, 155));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("ID Lagu");
        pnlLagu.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdSong.setBackground(new java.awt.Color(255, 255, 255));
        txtIdSong.setForeground(new java.awt.Color(0, 0, 0));
        txtIdSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSongActionPerformed(evt);
            }
        });
        pnlLagu.add(txtIdSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtStatusSong.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusSong.setForeground(new java.awt.Color(0, 0, 0));
        pnlLagu.add(txtStatusSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, -1));

        jLabel38.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Status Lagu");
        pnlLagu.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 110, -1));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("File Lagu");
        pnlLagu.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        txtFileSong.setBackground(new java.awt.Color(255, 255, 255));
        txtFileSong.setForeground(new java.awt.Color(0, 0, 0));
        pnlLagu.add(txtFileSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        txtDurationSong.setBackground(new java.awt.Color(255, 255, 255));
        txtDurationSong.setForeground(new java.awt.Color(0, 0, 0));
        txtDurationSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationSongActionPerformed(evt);
            }
        });
        pnlLagu.add(txtDurationSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Durasi Lagu");
        pnlLagu.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Content.add(pnlLagu, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("APLIKASI MANAJEMEN AUDIO SHOLAWAT");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(51, 153, 255));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnArtis.setBackground(new java.awt.Color(51, 204, 255));
        btnArtis.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnArtis.setForeground(new java.awt.Color(0, 0, 0));
        btnArtis.setText("ARTIS");
        btnArtis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtisActionPerformed(evt);
            }
        });

        btnAlbum.setBackground(new java.awt.Color(51, 204, 255));
        btnAlbum.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAlbum.setForeground(new java.awt.Color(0, 0, 0));
        btnAlbum.setText("ALBUM");
        btnAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumActionPerformed(evt);
            }
        });

        btnKategori.setBackground(new java.awt.Color(51, 204, 255));
        btnKategori.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKategori.setForeground(new java.awt.Color(0, 0, 0));
        btnKategori.setText("KATEGORI LAGU");
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(51, 204, 255));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnLagu.setBackground(new java.awt.Color(51, 204, 255));
        btnLagu.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnLagu.setForeground(new java.awt.Color(0, 0, 0));
        btnLagu.setText("LAGU");
        btnLagu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlbum)
                    .addComponent(btnArtis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKategori, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLagu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlbum, btnArtis, btnKategori, btnLagu});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnArtis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlbum)
                .addGap(18, 18, 18)
                .addComponent(btnKategori)
                .addGap(18, 18, 18)
                .addComponent(btnLagu)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlbum, btnArtis, btnKategori, btnLagu});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnArtisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtisActionPerformed
        Content.removeAll(); 
        Content.add(pnlArtis);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnArtisActionPerformed

    private void btnAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumActionPerformed
        Content.removeAll(); 
        Content.add(pnlAlbum);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnAlbumActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        Content.removeAll(); 
        Content.add(pnlKategori);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLaguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaguActionPerformed
        Content.removeAll(); 
        Content.add(pnlLagu);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnLaguActionPerformed

    private void txtCariArtistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariArtistKeyReleased
        String c = txtCariArtist.getText();
        // Pola 01 (Tidak Aman) sesuai contoh Anda
        String cari = "SELECT*FROM Artist WHERE id LIKE '%"+c+"%'"+
                      "OR name LIKE '%"+c+"%' OR description LIKE '%"+c+"%'"+
                      "OR status LIKE '%"+c+"%'";
        mycode.tampilDataArtist(tabelArtist, cari);
    }//GEN-LAST:event_txtCariArtistKeyReleased

    private void btnUbhArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhArtActionPerformed
        try {
            mycode.ubahArtist(txtIdArtist.getText(), txtNameArtist.getText(), 
                              txtDescArtist.getText(), txtStatusArtist.getText());

            // Refresh tabel
            mycode.tampilDataArtist(tabelArtist, "SELECT*FROM Artist");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhArtActionPerformed

    private void btnSmpnArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnArtActionPerformed
        try {
            if(txtIdArtist.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Artist Belum Diisi");
                txtIdArtist.requestFocus();
            } else if(txtNameArtist.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Name Belum Diisi");
                txtNameArtist.requestFocus();
            } else if(txtDescArtist.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Description Belum Diisi");
                txtDescArtist.requestFocus();
            } else if(txtStatusArtist.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusArtist.requestFocus();
            } else {
                mycode.simpanArtist02(txtIdArtist.getText(), txtNameArtist.getText(), 
                                      txtDescArtist.getText(), txtStatusArtist.getText()); 
                mycode.tampilDataArtist(tabelArtist, "SELECT*FROM Artist");
                if (mycode.duplikasi == true){
                    txtNameArtist.setText(mycode.CEK_NAME_ARTIST);
                    txtDescArtist.setText(mycode.CEK_DESC_ARTIST);
                    txtStatusArtist.setText(mycode.CEK_STATUS_ARTIST);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnArtActionPerformed

    private void btnHpsArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsArtActionPerformed
        try {
            mycode.hapusArtist(txtIdArtist.getText());
            mycode.tampilDataArtist(tabelArtist, "SELECT*FROM Artist");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsArtActionPerformed

    private void txtNameArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameArtistActionPerformed

    private void txtIdArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdArtistActionPerformed

    private void txtArtistIdAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistIdAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistIdAlbumActionPerformed

    private void btnHpsAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsAlbumActionPerformed
        try {
            mycode.hapusAlbum(txtIdAlbum.getText());
            mycode.tampilDataAlbum(tabelAlbum, "SELECT*FROM Album");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsAlbumActionPerformed

    private void btnSmpnAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnAlbumActionPerformed
        try {
            if(txtIdAlbum.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Album Belum Diisi");
                txtIdAlbum.requestFocus();
            } else if(txtArtistIdAlbum.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Artist ID Belum Diisi");
                txtArtistIdAlbum.requestFocus();
            } else if(txtNameAlbum.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Name Belum Diisi");
                txtNameAlbum.requestFocus();
            } else if(txtDescAlbum.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Description Belum Diisi");
                txtDescAlbum.requestFocus();
            } else if(txtStatusAlbum.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusAlbum.requestFocus();
            } else {
                mycode.simpanAlbum02(txtIdAlbum.getText(), txtArtistIdAlbum.getText(),
                                     txtNameAlbum.getText(), txtDescAlbum.getText(),
                                     txtStatusAlbum.getText());

                mycode.tampilDataAlbum(tabelAlbum, "SELECT*FROM Album");

                if (mycode.duplikasi == true){
                    txtArtistIdAlbum.setText(mycode.CEK_ARTIST_ID_ALBUM);
                    txtNameAlbum.setText(mycode.CEK_NAME_ALBUM);
                    txtDescAlbum.setText(mycode.CEK_DESC_ALBUM);
                    txtStatusAlbum.setText(mycode.CEK_STATUS_ALBUM);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnAlbumActionPerformed

    private void btnUbhAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhAlbumActionPerformed
        try {
            mycode.ubahAlbum(txtIdAlbum.getText(), txtArtistIdAlbum.getText(),
                             txtNameAlbum.getText(), txtDescAlbum.getText(),
                             txtStatusAlbum.getText());

            mycode.tampilDataAlbum(tabelAlbum, "SELECT*FROM Album");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhAlbumActionPerformed

    private void txtCariAlbumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariAlbumKeyReleased
        String c = txtCariAlbum.getText();
        String cari = "SELECT*FROM Album WHERE id LIKE '%"+c+"%'"+
                      "OR artist_id LIKE '%"+c+"%' OR name LIKE '%"+c+"%'"+
                      "OR description LIKE '%"+c+"%' OR status LIKE '%"+c+"%'";
        mycode.tampilDataAlbum(tabelAlbum, cari);
    }//GEN-LAST:event_txtCariAlbumKeyReleased

    private void txtIdAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAlbumActionPerformed

    private void txtNameCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCategoryActionPerformed

    private void btnHpsCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsCategoryActionPerformed
        try {
            mycode.hapusCategory(txtIdCategory.getText());
            mycode.tampilDataCategory(tabelCategory, "SELECT*FROM PlaylistSongCategory");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsCategoryActionPerformed

    private void btnSmpnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnCategoryActionPerformed
        try {
            if(txtIdCategory.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Category Belum Diisi");
                txtIdCategory.requestFocus();
            } else if(txtNameCategory.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Name Belum Diisi");
                txtNameCategory.requestFocus();
            } else if(txtDescCategory.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Description Belum Diisi");
                txtDescCategory.requestFocus();
            } else if(txtStatusCategory.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusCategory.requestFocus();
            } else {
                mycode.simpanCategory02(txtIdCategory.getText(), txtNameCategory.getText(),
                                      txtDescCategory.getText(), txtStatusCategory.getText());
                mycode.tampilDataCategory(tabelCategory, "SELECT*FROM PlaylistSongCategory");
                if (mycode.duplikasi == true){
                    txtNameCategory.setText(mycode.CEK_NAME_CATEGORY);
                    txtDescCategory.setText(mycode.CEK_DESC_CATEGORY);
                    txtStatusCategory.setText(mycode.CEK_STATUS_CATEGORY);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnCategoryActionPerformed

    private void btnUbhCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhCategoryActionPerformed
        try {
            mycode.ubahCategory(txtIdCategory.getText(), txtNameCategory.getText(),
                              txtDescCategory.getText(), txtStatusCategory.getText());
            mycode.tampilDataCategory(tabelCategory, "SELECT*FROM PlaylistSongCategory");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhCategoryActionPerformed

    private void txtCariCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariCategoryKeyReleased
        String c = txtCariCategory.getText();
        String cari = "SELECT*FROM PlaylistSongCategory WHERE id LIKE '%"+c+"%'"+
                      "OR name LIKE '%"+c+"%' OR description LIKE '%"+c+"%'"+
                      "OR status LIKE '%"+c+"%'";
        mycode.tampilDataCategory(tabelCategory, cari);
    }//GEN-LAST:event_txtCariCategoryKeyReleased

    private void txtIdCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCategoryActionPerformed

    private void txtCategoryIdSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryIdSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryIdSongActionPerformed

    private void btnHpsSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsSongActionPerformed
        try {
            mycode.hapusSong(txtIdSong.getText());
            mycode.tampilDataSong(tabelSong, "SELECT*FROM PlaylistSong");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsSongActionPerformed

    private void btnSmpnSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnSongActionPerformed
        try {
            if(txtIdSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Song Belum Diisi");
                txtIdSong.requestFocus();
            } else if(txtCategoryIdSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Category ID Belum Diisi");
                txtCategoryIdSong.requestFocus();
            } else if(txtAlbumIdSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Album ID Belum Diisi");
                txtAlbumIdSong.requestFocus();
            } else if(txtTitleSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Title Belum Diisi");
                txtTitleSong.requestFocus();
            } else if(txtDurationSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Duration Belum Diisi");
                txtDurationSong.requestFocus();
            } else if(txtFileSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "File Belum Diisi");
                txtFileSong.requestFocus();
            } else if(txtStatusSong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusSong.requestFocus();
            } else {
                mycode.simpanSong02(txtIdSong.getText(), txtCategoryIdSong.getText(),
                                      txtAlbumIdSong.getText(), txtTitleSong.getText(),
                                      txtDurationSong.getText(), txtFileSong.getText(),
                                      txtStatusSong.getText());

                mycode.tampilDataSong(tabelSong, "SELECT*FROM PlaylistSong");

                if (mycode.duplikasi == true){
                    txtCategoryIdSong.setText(mycode.CEK_CATEGORY_ID_SONG);
                    txtAlbumIdSong.setText(mycode.CEK_ALBUM_ID_SONG);
                    txtTitleSong.setText(mycode.CEK_TITLE_SONG);
                    txtDurationSong.setText(mycode.CEK_DURATION_SONG);
                    txtFileSong.setText(mycode.CEK_FILE_SONG);
                    txtStatusSong.setText(mycode.CEK_STATUS_SONG);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnSongActionPerformed

    private void btnUbhSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhSongActionPerformed
        try {
            mycode.ubahSong(txtIdSong.getText(), txtCategoryIdSong.getText(),
                              txtAlbumIdSong.getText(), txtTitleSong.getText(),
                              txtDurationSong.getText(), txtFileSong.getText(),
                              txtStatusSong.getText());

            mycode.tampilDataSong(tabelSong, "SELECT*FROM PlaylistSong");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhSongActionPerformed

    private void txtCariSongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariSongKeyReleased
        String c = txtCariSong.getText();
        String cari = "SELECT*FROM PlaylistSong WHERE id LIKE '%"+c+"%'"+
                      "OR playlist_song_category_id LIKE '%"+c+"%' OR album_id LIKE '%"+c+"%'"+
                      "OR title LIKE '%"+c+"%' OR duration LIKE '%"+c+"%'"+
                      "OR file LIKE '%"+c+"%' OR status LIKE '%"+c+"%'";
        mycode.tampilDataSong(tabelSong, cari);
    }//GEN-LAST:event_txtCariSongKeyReleased

    private void txtIdSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSongActionPerformed

    private void txtDurationSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationSongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnAlbum;
    private javax.swing.JButton btnArtis;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsAlbum;
    private javax.swing.JButton btnHpsArt;
    private javax.swing.JButton btnHpsCategory;
    private javax.swing.JButton btnHpsSong;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnLagu;
    private javax.swing.JButton btnSmpnAlbum;
    private javax.swing.JButton btnSmpnArt;
    private javax.swing.JButton btnSmpnCategory;
    private javax.swing.JButton btnSmpnSong;
    private javax.swing.JButton btnUbhAlbum;
    private javax.swing.JButton btnUbhArt;
    private javax.swing.JButton btnUbhCategory;
    private javax.swing.JButton btnUbhSong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pnlAlbum;
    private javax.swing.JPanel pnlArtis;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKategori;
    private javax.swing.JPanel pnlLagu;
    private javax.swing.JTable tabelAlbum;
    private javax.swing.JTable tabelArtist;
    private javax.swing.JTable tabelCategory;
    private javax.swing.JTable tabelSong;
    private javax.swing.JTextField txtAlbumIdSong;
    private javax.swing.JTextField txtArtistIdAlbum;
    private javax.swing.JTextField txtCariAlbum;
    private javax.swing.JTextField txtCariArtist;
    private javax.swing.JTextField txtCariCategory;
    private javax.swing.JTextField txtCariSong;
    private javax.swing.JTextField txtCategoryIdSong;
    private javax.swing.JTextField txtDescAlbum;
    private javax.swing.JTextField txtDescArtist;
    private javax.swing.JTextField txtDescCategory;
    private javax.swing.JTextField txtDurationSong;
    private javax.swing.JTextField txtFileSong;
    private javax.swing.JTextField txtIdAlbum;
    private javax.swing.JTextField txtIdArtist;
    private javax.swing.JTextField txtIdCategory;
    private javax.swing.JTextField txtIdSong;
    private javax.swing.JTextField txtNameAlbum;
    private javax.swing.JTextField txtNameArtist;
    private javax.swing.JTextField txtNameCategory;
    private javax.swing.JTextField txtStatusAlbum;
    private javax.swing.JTextField txtStatusArtist;
    private javax.swing.JTextField txtStatusCategory;
    private javax.swing.JTextField txtStatusSong;
    private javax.swing.JTextField txtTitleSong;
    // End of variables declaration//GEN-END:variables
}
